/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrental;

import java.sql.*;
import java.lang.*;
import javax.swing.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;


public class car_details extends javax.swing.JFrame {
   // private Connection con;
      //Connection connection = null;
      //Statement statement = null;
      ResultSet resultSet = null;
      String car,car2;
    /**
     * Creates new form car_details
     */
    public car_details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        quantity_field = new javax.swing.JTextField();
        price_per_day_field = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        submit_button2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        seating_capacity_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        car_type = new javax.swing.JComboBox<>();
        car_type_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quantity_field.setEditable(false);
        quantity_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_fieldActionPerformed(evt);
            }
        });

        price_per_day_field.setEditable(false);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        submit_button2.setText("Submit");
        submit_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_button2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Car:");

        jLabel2.setText("Quantity Available:");

        jLabel3.setText("Price Per Day:");

        jLabel4.setText("Car Capacity:");

        seating_capacity_field.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setText("Select Car:");

        jLabel7.setText("Select Car Type:");

        car_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatchback", "Sedan", "SUV", "Premium" }));

        car_type_button.setText("Submit");
        car_type_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_type_buttonActionPerformed(evt);
            }
        });

        jButton3.setText("Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel8.setText("Customer Details:");

        jLabel9.setText("Name: ");

        jLabel10.setText("Phone:");

        jLabel11.setText("Email Id:");

        jLabel13.setText("No. of Days:");

        jLabel12.setText("License Number:");

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seating_capacity_field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, 0, 100, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addComponent(submit_button2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(car_type, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(car_type_button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantity_field, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(price_per_day_field))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(car_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car_type_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit_button2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(seating_capacity_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_per_day_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 69, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantity_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_fieldActionPerformed
  
    }//GEN-LAST:event_quantity_fieldActionPerformed

    private void submit_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_button2ActionPerformed
      car2= (String)jComboBox1.getSelectedItem();
      //car = (String)car_type.getSelectedItem();
        if(car.equalsIgnoreCase("Sedan"))
        {
             
        try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
               //statement=con.createStatement();
               PreparedStatement ps = con.prepareStatement("SELECT Seating_capacity,Price_per_day,Quantity_available FROM `car_detail_sedan` where car_name=?;");
               //resultSet=statement.executeQuery("SELECT car_seating_capacity,price_per_day,quantity_available FROM `car_detail_sedan` where car_name=?;");
               ps.setString(1,car2);
               resultSet=ps.executeQuery();
               
               while(resultSet.next()){
               //System.out.printf("%s",resultSet.getString(1));
               String seating_capacity = resultSet.getString(1);
               //String price = resultSet.getString(2);
               String quantity = resultSet.getString(3);
               quantity_field.setText(quantity);
               price_per_day_field.setText(resultSet.getString(2));
               seating_capacity_field.setText(seating_capacity);
               System.out.println(quantity_field);
               
              //JOptionPane.showMessageDialog(null,seating_capacity +"\n"+price_per_day_field+"\n"+ quantity);
                
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
        }
        else if(car.equalsIgnoreCase("hatchback"))
        {
             
        try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
               //statement=con.createStatement();
               PreparedStatement ps = con.prepareStatement("SELECT Seating_capacity,Price_per_day,Quantity_available FROM `car_detail_hatchback` where car_name=?;");
               //resultSet=statement.executeQuery("SELECT car_seating_capacity,price_per_day,quantity_available FROM `car_detail_sedan` where car_name=?;");
               ps.setString(1,car2);
               resultSet=ps.executeQuery();
               
               while(resultSet.next()){
               //System.out.printf("%s",resultSet.getString(1));
               String seating_capacity = resultSet.getString(1);
               //String price = resultSet.getString(2);
               String quantity = resultSet.getString(3);
               quantity_field.setText(quantity);
               price_per_day_field.setText(resultSet.getString(2));
               seating_capacity_field.setText(seating_capacity);
               System.out.println(quantity_field);
               
              //JOptionPane.showMessageDialog(null,seating_capacity +"\n"+price_per_day_field+"\n"+ quantity);
                
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
        }
       else if(car.equalsIgnoreCase("suv"))
        {
             
        try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
               //statement=con.createStatement();
               PreparedStatement ps = con.prepareStatement("SELECT Seating_capacity,Price_per_day,Quantity_available FROM `car_detail_suv` where car_name=?;");
               //resultSet=statement.executeQuery("SELECT car_seating_capacity,price_per_day,quantity_available FROM `car_detail_sedan` where car_name=?;");
               ps.setString(1,car2);
               resultSet=ps.executeQuery();
               
               while(resultSet.next()){
               //System.out.printf("%s",resultSet.getString(1));
               String seating_capacity = resultSet.getString(1);
               //String price = resultSet.getString(2);
               String quantity = resultSet.getString(3);
               quantity_field.setText(quantity);
               price_per_day_field.setText(resultSet.getString(2));
               seating_capacity_field.setText(seating_capacity);
               System.out.println(quantity_field);
               
              //JOptionPane.showMessageDialog(null,seating_capacity +"\n"+price_per_day_field+"\n"+ quantity);
                
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
        }
        else if(car.equalsIgnoreCase("premium"))
        {
             
        try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
               //statement=con.createStatement();
               PreparedStatement ps = con.prepareStatement("SELECT Seating_capacity,Price_per_day,Quantity_available FROM `car_detail_luxorious` where car_name=?;");
               //resultSet=statement.executeQuery("SELECT car_seating_capacity,price_per_day,quantity_available FROM `car_detail_sedan` where car_name=?;");
               ps.setString(1,car2);
               resultSet=ps.executeQuery();
               
               while(resultSet.next()){
               //System.out.printf("%s",resultSet.getString(1));
               String seating_capacity = resultSet.getString(1);
               //String price = resultSet.getString(2);
               String quantity = resultSet.getString(3);
               quantity_field.setText(quantity);
               price_per_day_field.setText(resultSet.getString(2));
               seating_capacity_field.setText(seating_capacity);
               System.out.println(quantity_field);
               
              //JOptionPane.showMessageDialog(null,seating_capacity +"\n"+price_per_day_field+"\n"+ quantity);
                
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
        }
       
    }//GEN-LAST:event_submit_button2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void car_type_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_type_buttonActionPerformed
   car = (String)car_type.getSelectedItem();
         JOptionPane.showMessageDialog(null,car_type.getSelectedItem());
    if(car.equalsIgnoreCase("Sedan"))
    {        jComboBox1.removeAllItems();
           try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
              PreparedStatement ps = con.prepareStatement("SELECT * FROM `car_detail_sedan`");
              resultSet=ps.executeQuery();
              while(resultSet.next()){
               
               String car_name = resultSet.getString("car_name");            
               jComboBox1.addItem(car_name );
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
            
    }
    else if(car.equalsIgnoreCase("SUV"))
    {        jComboBox1.removeAllItems();
           try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
              PreparedStatement ps = con.prepareStatement("SELECT * FROM `car_detail_suv`");
              resultSet=ps.executeQuery();
              while(resultSet.next()){
               
               String car_name = resultSet.getString("car_name");            
               jComboBox1.addItem(car_name );
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
            
    }
    else if(car.equalsIgnoreCase("hatchback"))
    {        jComboBox1.removeAllItems();
           try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
              PreparedStatement ps = con.prepareStatement("SELECT * FROM `car_detail_hatchback`");
              resultSet=ps.executeQuery();
              while(resultSet.next()){
               
               String car_name = resultSet.getString("car_name");            
               jComboBox1.addItem(car_name );
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
            
    }       
    else if(car.equalsIgnoreCase("premium"))
    {        jComboBox1.removeAllItems();
           try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","");
              PreparedStatement ps = con.prepareStatement("SELECT * FROM `car_detail_luxorious`");
              resultSet=ps.executeQuery();
              while(resultSet.next()){
               
               String car_name = resultSet.getString("car_name");            
               jComboBox1.addItem(car_name );
         }

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
            
    }
       
            
    }//GEN-LAST:event_car_type_buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String name= jTextField1.getText();
        String phone= jTextField2.getText();
        String email= jTextField3.getText();
        String license= jTextField4.getText();
        String days= jTextField5.getText();
        String price = price_per_day_field.getText();
        
        try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              PreparedStatement ps;
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental","root","")) {
                ps = conn.prepareStatement("INSERT INTO `customer_details` (`name`, `phone_number`, `email`,`car_type`,`car_selected`, `no_of_days`,`license`,`price_per_day`) VALUES (?, ?, ?, ?, ?, ?, ?, ?);");
                ps.setString(1,name);
                ps.setString(2,phone);
                ps.setString(3,email);
                ps.setString(4,car);
                ps.setString(5,car2);
                ps.setString(6,days);
                ps.setString(7,license);
                ps.setString(8,price);
                int result = ps.executeUpdate();  
                if(result==1)
                {
                    JOptionPane.showMessageDialog(null,name + " added successfully !", "Add successfull",JOptionPane.PLAIN_MESSAGE);
                     new billing().setVisible(true);
                     dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Unknown Error");
                }
            }
            ps.close();
         

             }
            catch(Exception ex)
            {
            ex.printStackTrace();
            }
      
 

         
         
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(car_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(car_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(car_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(car_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new car_details().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> car_type;
    private javax.swing.JButton car_type_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField price_per_day_field;
    private javax.swing.JTextField quantity_field;
    private javax.swing.JTextField seating_capacity_field;
    private javax.swing.JButton submit_button2;
    // End of variables declaration//GEN-END:variables
}
